"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useOnOutsideClick = exports.useDynamicRefs = exports.useDebounce = exports.useBodyLock = exports.useTouch = exports.useWindowSize = exports.useCopyText = exports.useLocalStorage = exports.usePreventAnimation = void 0;
var usePreventAnimation_1 = __importDefault(require("./usePreventAnimation"));
exports.usePreventAnimation = usePreventAnimation_1.default;
var useLocalStorage_1 = __importDefault(require("./useLocalStorage"));
exports.useLocalStorage = useLocalStorage_1.default;
var useCopyText_1 = __importDefault(require("./useCopyText"));
exports.useCopyText = useCopyText_1.default;
var useWindowSize_1 = __importDefault(require("./useWindowSize"));
exports.useWindowSize = useWindowSize_1.default;
var useTouch_1 = __importDefault(require("./useTouch"));
exports.useTouch = useTouch_1.default;
var useBodyLock_1 = __importDefault(require("./useBodyLock"));
exports.useBodyLock = useBodyLock_1.default;
var useOnOutsideClick_1 = __importDefault(require("./useOnOutsideClick"));
exports.useOnOutsideClick = useOnOutsideClick_1.default;
var useDebounce_1 = __importDefault(require("./useDebounce"));
exports.useDebounce = useDebounce_1.default;
var useDynamicRefs_1 = __importDefault(require("./useDynamicRefs"));
exports.useDynamicRefs = useDynamicRefs_1.default;
